#! /usr/bin/env python
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time

driver = webdriver.Chrome('/home/mehdi/Documents/chromedriver')
driver.get('https://facebook.com')
try:
    email = 'fati.fati.870@outlook.com'
    password = '^ZWMG6z26/nBSw.'
    user_name_element = driver.find_element_by_id('email')
    pass_element = driver.find_element_by_id('pass')
    user_name_element.send_keys(email)
    pass_element.send_keys(password)
    pass_element.send_keys(Keys.ENTER)
except:
    print('not found')
