#!/bin/python

def splt(e):
    a, b = e.split(' ')
    return int(a) / int(b)

with open("/home/mehdi/Documents/the information/tya") as f:
    raw = f.read()

l = raw.strip().split('\n')
n_inputs = len(l)

l = map(splt, l)
result = sum(l) / n_inputs 

print(f"{result * 100:.3f}%")
